name: repo_initialization

on:
  push:
    branches:
      - main

jobs:
  repo_initialization:
    runs-on: ubuntu-latest
    if: ${{ github.event.created && github.repository != 'ayungavis/nextjs-tailwind-boilerplate' }}
    steps:
      - uses: actions/checkout@v4
      - name: Replace README and LICESE
        run: |
          mv README.template.md README.md
          mv LICENSE.template LICENSE
      - name: Replace placholders
        id: replace_placeholders
        uses: garronej/ts-ci@v2.1.5
        with:
          action_name: string_replace
          input_string: ${{github.event.repository.name}}
          search_value: '-'
          replace_value: '_'
      - name: Replace tokens in README and package.json
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["README.md", "package.json", "LICENSE"]'
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          USER_OR_ORG: ${{ github.repository_owner }}
          DESC: ${{ github.event.repository.description }}
          REPO_NAME_NO_DASHES: ${{ steps.replace_placeholders.outputs.replace_result }}
      - name: Remove this workflow and dependabot, it only needs to be run once
        run: |
          rm .github/workflows/repo_initialization.yaml
          rm .github/dependabot.yaml
      - name: Commit files
        run: |
          git config --local user.email "ayungavis@gmail.com"
          git config --local user.name "NextJS Tailwind Boilerplate"
          git commit -am "Replacing placeholders"
      - name: Push changes (if fails, please read the readme and try again)
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          branch: main
  debug:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'ayungavis/nextjs-tailwind-boilerplate' }}
    steps:
      - name: Show envs
        run: env
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
